In [1]:
import numpy as np

A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12]])
b = np.array([9, 15, 35])
x = np.linalg.solve(A, b)
x


array([-0.58226371,  3.22870478, -1.98599767])

In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


In [126]:
westValley = pd.read_csv('PNWDistrictWestValleyEvent2020.csv')
westValley.shape


(61, 9)

In [47]:
westValley['Red1'].head()

0    4911
1    2605
2    3693
3    4089
4    4980
Name: Red1, dtype: int64

In [140]:
fullTeamList = np.concatenate((westValley['Red1'], westValley['Red2'], westValley['Red3'], westValley['Blue1'], westValley['Blue2'], westValley['Blue3']))
fullTeamList = np.sort(fullTeamList)
fullTeamList

array([1595, 1595, 1595, 1595, 1595, 1595, 1595, 1595, 1595, 1595, 1595,
       1595, 1595, 1595, 1595, 1595, 2147, 2147, 2147, 2147, 2147, 2147,
       2147, 2147, 2147, 2147, 2147, 2147, 2147, 2147, 2147, 2147, 2605,
       2605, 2605, 2605, 2605, 2605, 2605, 2605, 2605, 2605, 2605, 2605,
       2605, 2605, 2811, 2811, 2811, 2811, 2811, 2811, 2811, 2811, 2811,
       2811, 2811, 2811, 2811, 2811, 2811, 2811, 2910, 2910, 2910, 2910,
       2910, 2910, 2910, 2910, 2910, 2910, 2910, 2910, 2910, 2910, 2910,
       2910, 2944, 2944, 2944, 2944, 2944, 2944, 2944, 2944, 2944, 2944,
       2944, 2944, 3663, 3663, 3663, 3663, 3663, 3663, 3663, 3663, 3663,
       3663, 3663, 3663, 3663, 3663, 3663, 3663, 3663, 3663, 3663, 3693,
       3693, 3693, 3693, 3693, 3693, 3693, 3693, 3693, 3693, 3693, 3693,
       3693, 3693, 3693, 3693, 3711, 3711, 3711, 3711, 3711, 3711, 3711,
       3711, 3711, 3711, 3711, 3711, 3711, 3711, 3711, 3711, 3712, 3712,
       3712, 3712, 3712, 3712, 3712, 3712, 3712, 37

In [128]:
teamList = np.unique(fullTeamList)
teamList

array([1595, 2147, 2605, 2811, 2910, 2944, 3663, 3693, 3711, 3712, 3876,
       4060, 4061, 4089, 4104, 4125, 4513, 4692, 4911, 4980, 5920, 6076,
       6442, 6443], dtype=int64)

In [129]:
teamList.shape[0]

24

In [130]:
numberOfMatchs = westValley['Match'].count()
numberOfMatchs

61

In [131]:
x = np.where(teamList == 4089)
x[0][0]

13

In [132]:
Teams = np.zeros((numberOfMatchs*2,teamList.shape[0]))
TeamsPrime = np.zeros((teamList.shape[0],numberOfMatchs*2))
Teams.shape

(122, 24)

In [133]:
Scores = np.concatenate((westValley['RedScore'],westValley['BlueScore']))
Scores.shape

(122,)

In [134]:
westValley['Red1'][0]

4911

In [135]:
for row in range(numberOfMatchs):
    x = np.where(teamList == westValley['Red1'][row])
    Teams[row][x[0][0]] = 1
    TeamsPrime[x[0][0]][row] = 1
    x = np.where(teamList == westValley['Red2'][row])
    Teams[row][x[0][0]] = 1
    TeamsPrime[x[0][0]][row] = 1
    x = np.where(teamList == westValley['Red3'][row])
    Teams[row][x[0][0]] = 1
    TeamsPrime[x[0][0]][row] = 1
    x = np.where(teamList == westValley['Blue1'][row])
    Teams[numberOfMatchs+row][x[0][0]] = 1
    TeamsPrime[x[0][0]][numberOfMatchs+row] = 1
    x = np.where(teamList == westValley['Blue2'][row])
    Teams[numberOfMatchs+row][x[0][0]] = 1
    TeamsPrime[x[0][0]][numberOfMatchs+row] = 1
    x = np.where(teamList == westValley['Blue3'][row])
    Teams[numberOfMatchs+row][x[0][0]] = 1
    TeamsPrime[x[0][0]][numberOfMatchs+row] = 1
Teams.shape

(122, 24)

In [136]:
TeamsTotal = np.matmul(TeamsPrime,Teams)
ScoresTotal = np.matmul(TeamsPrime,Scores)
print(TeamsTotal.shape)
print(ScoresTotal.shape)

(24, 24)
(24,)


In [153]:
OPRs = np.linalg.solve(RedTeamsTotal, RedScoresTotal)
OPRs

array([ 2.65212034e+01,  4.24441842e+01,  2.95336121e+01,  6.45513722e+01,
        9.99224131e+01, -8.36981238e+00,  6.24629168e+01,  2.06713532e+01,
        6.04957322e+01,  7.73372702e+00, -6.94355861e+00,  1.27762142e+01,
        1.68659719e+01,  6.34268300e+01,  2.67877793e+01,  3.78174627e+01,
        6.64036356e+01,  2.38332094e+01,  1.08909224e+02, -2.10645278e-03,
        5.70220154e+01, -2.48121066e+00,  1.22962114e+01,  2.51727923e+01])

In [154]:
OPRArray = []
for row in range(OPRs.shape[0]):
    print(str(teamList[row]) + " "+ str(OPRs[row]))
    OPRArray.append((OPRs[row],teamList[row]))
 #   print(teamNumber = teamList[row].str() + " "+ OPRs[row].str())

1595 26.52120339745753
2147 42.444184164894665
2605 29.533612136876155
2811 64.5513722309477
2910 99.92241309953079
2944 -8.369812380693286
3663 62.46291681275935
3693 20.67135324826187
3711 60.495732224393066
3712 7.733727016299237
3876 -6.943558606550616
4060 12.776214151971043
4061 16.86597191225603
4089 63.426830019347925
4104 26.787779315133815
4125 37.81746266193912
4513 66.40363560083202
4692 23.8332093896483
4911 108.90922392904999
4980 -0.0021064527775261025
5920 57.022015443698265
6076 -2.481210657672267
6442 12.296211440391302
6443 25.17279225797401
